system:
  host: 0.0.0.0
  port: 8080
  env: test

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  db: gin_vue
  log_level: dev

logger:
  level: info
  prefix: "[gin_project]"
  director: log
  show_line: true
  log_in_console: true